spring:
  cloud:
    function:
      definition: convertFtoC
    stream:
      default-binder: local-solace
      bindings:
        convertFtoC-in-0:
          destination: TEMPS.Q
          group: PROCESSOR
        convertFtoC-out-0:
          destination: sensor/temperature/celsius
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55557
                msgVpn: default
                clientUsername: default
                clientPassword: default

      solace:
        default:
          consumer:
            add-destination-as-subscription-to-queue: false
            provision-durable-queue: false
            provision-error-queue: false
            queue-name-expression: "destination"

#        bindings:
#          convertFtoC-in-0:
#            consumer:
#              queueAdditionalSubscriptions: sensor/temperature/fahrenheit

management:
  tracing:
    sampling:
      probability: 1

#tracing.url: http://localhost:14317

server:
  port: 0